services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./config:/cv/config
    environment:
      CONFIG_PATH: config/prod.yaml
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["sh", "-c", "templ generate && go run cmd/main.go --env=.env"]
