services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./config:/cv/config
    environment:
      CONFIG_PATH: config/prod.yaml
    cokmand: ["sh", "-c", "templ generate && go run cmd/main.go --env=.env"]
