services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/productiondb --quiet
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - ./config:/cv/config
    environment:
      CONFIG_PATH: config/prod.yaml
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["sh", "-c", "templ generate && go run cmd/main.go --env=.env"]

volumes:
  mongo-data:
