env: "local" # local, dev, prod
http_server:
  address: "localhost:3000"
  timeout: 5s
  idle_timeout: 60s
database:
  client_uri: "mongodb://localhost:27017/"
  database: "alex_cv"
  collection: "cv_collection"
  user: root
  password: root
