// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AboutComponent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"py-5 py-md-7 bg-dark\" id=\"about\"><div class=\"binary-bg\"></div><div class=\"container\"><div class=\"d-flex flex-column justify-content-center align-items-center\"><div class=\"about-content-text col-lg-6 mb-4 mb-lg-0\"><div class=\"d-flex justify-content-start\"><h2 class=\"section-heading\">About Me</h2></div><p class=\"lead\">Hey, I’m Alex! With nearly seven years of experience in web and mobile development, I specialize in JavaScript and TypeScript, primarily within the Vue ecosystem (Vue2, Vue3, Nuxt2, Nuxt3). My frontend expertise extends to testing with Vitest, Cypress, and Jest, as well as building scalable applications with Webpack and Vite. I’ve also developed cross-platform apps using Flutter, covering everything from LLM integrations to video streaming and music generation.</p><p>Beyond frontend, I build RESTful APIs with Go and PostgreSQL, handling payments, authentication, and LLM services. I also have experience in Python and C++ for business logic development. On the DevOps side, I’m proficient in Dockerizing applications, setting up Nginx, and configuring Linux servers. With nearly three years as a technical interviewer, I’ve helped shape engineering teams by evaluating top talent.</p><p>Fluent in English (C1), I thrive on collaboration and continuous learning. My ultimate goal is to lead tech teams as a CTO, driving innovative product development. Outside of coding, I enjoy jogging, hiking, studying languages, and reading. I also love spending time with my family - going hiking with my wife and children.</p></div></div></div></section><style>\n      @media (max-width: 576px) {\n        .about-content-text {\n          text-align: center;\n        }\n      }\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
